### ISSUE TITLE
turntable is driving wrong every 8. scan-step

### ISSUE THREAD

**Issue by pointhi** [francisengelmann/FabScan100#14]
I'm using a fabcube, without a turnable laser, and found out that the turntable is driving in the opposit direction every 8. scan-step and then (holding the position/driving back) for 2 or 3 steps.

Because of that, I cannot scan objects in a correct way. For example, a scanned cuboid is more like a rectangle with rounded surfaces.

The software is build from the repository on Ubuntu 14.04.

**Comment by mariolukas** [comment]
Mho sounds strange to me. Maybe there is a problem with you motor driver. Which hardware setup are you using? Fabscan Shield with Pololu motor driver?

**Comment by pointhi** [comment]
I'm using the fabscan shield, but not the Pololu motor driver, because I get a SilentStepStick as replacement for the fault Polulu.

In the control panel the stepper is always working correctly, so I'm thinking the scanner software has some problem, or is expecting a stepper-motor for the laser.

**Comment by pointhi** [comment]
ok, seems the overcurrent protection was configed to harsh, so the driver overheated and shut down for a few seconds (my therorie).

Correct behavior of the problem: 26 stepps, then 2 or 3 steps backward/stop, 8 steps normal, 2 or 3 steps backward/stop, 8 steps normal,....

**Comment by mariolukas** [comment]
Have you soldered all pin headers to the silent step stick driver ?

**Comment by pointhi** [comment]
no, I got an instruction pdf, in which was described how to solder the driver correctly

**Comment by mariolukas** [comment]
I am using the silent step sticks with the new fabscan software. I is better if you do not connect EN, CFG1, CFG2 and CFG3.

**Comment by pointhi** [comment]
In my pdf the silent step stick has only connected EN, STEP and DIR on the one side, on the other side all pins are connected

**Comment by mariolukas** [comment]
Thats from the TMC2100 Datasheet and the reason why i keep EN open (no connection). 

Y, ramp down from 100% to 34% motor current in 44M clock cycles (3 to 4 seconds) if no step pulse for more than 1M clock cycles (standstill). In combination with stealthChop be sure not to work with too low overall current setting, as regulation will not be able to measure the motor current after stand still current reduction. This will result in very low motor current after the stand-still period.
